### ISSUE TITLE
Legacy 게시판용 스크립트 지우기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/skin#66]
[Legacy 게시판](https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EC%9C%84%ED%82%A4%EC%99%80_%EC%99%84%EC%A0%84%ED%9E%88_%ED%86%B5%ED%95%A9%EB%90%9C_%EA%B2%8C%EC%8B%9C%ED%8C%90)이 개발·운영중이었으나 [스트럭처드 디스커션(구 'Flow' 혹은 번역명 '구조화된 토론') 도입 이후 교체](https://femiwiki.com/w/주제:Trmucewe05eblsev)되었습니다.

그러므로 Legacy 게시판 관련 코드를 지웁니다.

#### TODO
- [x] https://github.com/femiwiki/mediawiki/issues/214
- [x] https://github.com/femiwiki/skin/blob/master/resources/bbs.js 파일 삭제
- [x] https://github.com/femiwiki/skin/blob/master/resources/screen-bbs.less 파일 삭제
- [x] 위 파일들을 언급하는 모든 곳 수정

**Comment by lens0021** [comment]
[2019년 2월 23일 관련 배포 진행함](https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8/2019%EB%85%84#2.EC.9B.94_23.EC.9D.BC).
